test_messages:
  - content: {"text": "测试消息1"}
    expected_code: 0
    access_token: "t-g10472i07FSSPTIYJJZ2R63YWK5XZLC5VP7W5PCA"
    receive_id: "ou_adf4e416e22c12c5d4b40e347315f68c"
  - content: {"text": "Hello World2"}
    expected_code: 0
    access_token: "t-g10472eoYNVYZFYQXBH5WHKVMBP77MNIAWEIV22Y"
    receive_id: "ou_adf4e416e22c12c5d4b40e347315f68c"